apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.project }}
spec:
  selector:
    matchLabels:
      project: {{ .Values.project }}
      app: {{ .Values.app }}
      tier: back-end
  replicas: 1
  template:
    metadata:
      labels:
        project: {{ .Values.project }}
        app: {{ .Values.app }}
        tier: back-end
    spec:
      volumes:
      - name: public
        hostPath:
          path: /var/volumes/uploads
          type: Directory
      containers:
      - name: strapi
        image: 'deadpoolcr.azurecr.io/{{ .Values.image.repo }}:{{ .Values.image.tag }}'
        ports:
        - containerPort: {{ .Values.containerport }}
        volumeMounts:
        - mountPath: /usr/src/main/public/uploads
          name: public
        envFrom:
        - secretRef:
            name: sec